//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL55
{
    using System;
    
    public enum Gravidade : int
    {
        Alta = 0,
        Media = 1,
        Baixa = 2
    }
}
