//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL55
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remedio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Remedio()
        {
            this.DoencaRemedio = new HashSet<DoencaRemedio>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Intervalo { get; set; }
        public string Dosagem { get; set; }
        public int ReceitaId { get; set; }
        public bool ReterReceita { get; set; }
        public Tarja1 Tarja { get; set; }
    
        public virtual Receita Receita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoencaRemedio> DoencaRemedio { get; set; }
    }
}
